### ISSUE TITLE
Missing "Global_PA" region for curtana device

### ISSUE THREAD

**Issue by hileth** [Project-Awaken/android_device_xiaomi_miatoll#2]
Since there are currently 4 known regions, let's add "Global_PA" region in init

```
else if (region == "Global_PA") {
            set_device_props("Redmi", "curtana", "Redmi Note 9S");
```
![screenshot](https://user-images.githubusercontent.com/95592417/144766492-e130623d-61d3-4196-a5f6-ce49cb572a72.jpg)

**Comment by BladeRunner-A2C** [comment]
You meant this maybe?
https://github.com/Project-Awaken/android_device_xiaomi_miatoll/commit/484533891e8fb796551c953e9c05b6a68c4dacae

**Comment by BladeRunner-A2C** [comment]
Closed due to no response.
